export const actionTypes = {
  GET_HOME_PHOTOS_PENDING: 'GET_HOME_PHOTOS_PENDING',
  GET_HOME_PHOTOS_SUCCESS: 'GET_HOME_PHOTOS_SUCCESS',
  GET_HOME_PHOTOS_ERROR: 'GET_HOME_PHOTOS_ERROR',
  GET_EXPLORE_PHOTOS_PENDING: 'GET_EXPLORE_PHOTOS_PENDING',
  GET_EXPLORE_PHOTOS_SUCCESS: 'GET_EXPLORE_PHOTOS_SUCCESS',
  GET_EXPLORE_PHOTOS_ERROR: 'GET_EXPLORE_PHOTOS_ERROR',
  GET_SEARCH_PHOTOS_PENDING: 'GET_SEARCH_PHOTOS_PENDING',
  GET_SEARCH_PHOTOS_SUCCESS: 'GET_SEARCH_PHOTOS_SUCCESS',
  GET_SEARCH_PHOTOS_ERROR: 'GET_SEARCH_PHOTOS_ERROR',
  SEARCH_TERM: 'SEARCH_TERM',
};
